name: &name {{name}}
version: 0.0.0
author: {{author}}

library:
    source-dirs: src

executable:
    main: Main.hs
    dependencies: *name
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    - -O2
    verbatim:
    - default-extensions: null
    - mixins: null

defaults: xnuk/xnuk@hpack
